language: java

addons:
  ssh_known_hosts:
  - ftp.interlis.ch

branches:
  only:
    - master
    - stable

install: true

before_script:

script: 
  - ./gradlew build 
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE publish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' -Ddownloads_pwd=${downloads_pwd} -Ddownloads_usr=jql_downloads  publish
    on:
      branch: stable
