language: java
jdk: openjdk11

addons:
  ssh_known_hosts:
  - ftp.interlis.ch

branches:
  only:
    - main
    - stable

install: true

before_script:

script: 
  - ./gradlew build 
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} publish
    on:
      branch: main
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_url=${repos_url} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} '-Drelease=' -Ddownloads_pwd=${downloads_pwd} -Ddownloads_usr=jql_downloads  publish
    on:
      branch: stable
